# Generated by Codex on 2026-05-23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless_mail", "0003_mailrule_stop_processing"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailrule",
            name="bundle_documents",
            field=models.BooleanField(
                default=False,
                help_text="If an email produces multiple documents, such as the rendered email body and attachments, group them into a bundle for easier navigation. The documents remain separate.",
                verbose_name="bundle documents created from the same email",
            ),
        ),
    ]
