# Generated by Codex on 2026-05-23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0021_widen_workflow_integer_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentBundle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        verbose_name="name",
                    ),
                ),
                (
                    "bundle_id",
                    models.CharField(
                        db_index=True,
                        help_text="Human-visible bundle identifier.",
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Bundle IDs may only contain A-Z, 0-9, and hyphens.",
                                regex="^[A-Z0-9-]+$",
                            ),
                        ],
                        verbose_name="bundle id",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
            ],
            options={
                "verbose_name": "document bundle",
                "verbose_name_plural": "document bundles",
                "ordering": ("bundle_id",),
            },
        ),
        migrations.CreateModel(
            name="DocumentBundleMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="order",
                    ),
                ),
                (
                    "bundle_item_name",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        verbose_name="bundle item name",
                    ),
                ),
                (
                    "bundle_item_type",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="bundle item type",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="documents.documentbundle",
                        verbose_name="bundle",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundle_memberships",
                        to="documents.document",
                        verbose_name="document",
                    ),
                ),
            ],
            options={
                "verbose_name": "document bundle membership",
                "verbose_name_plural": "document bundle memberships",
                "ordering": ("bundle", "order_id"),
            },
        ),
        migrations.AddConstraint(
            model_name="documentbundlemembership",
            constraint=models.UniqueConstraint(
                fields=("bundle", "order_id"),
                name="documents_bundle_membership_order_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentbundlemembership",
            constraint=models.UniqueConstraint(
                fields=("document",),
                name="documents_bundle_membership_document_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="documentbundlemembership",
            index=models.Index(fields=["document"], name="documents_bundle_doc_idx"),
        ),
        migrations.AddIndex(
            model_name="documentbundlemembership",
            index=models.Index(
                fields=["bundle", "order_id"],
                name="documents_bundle_order_idx",
            ),
        ),
    ]
