# Generated by Codex on 2026-05-23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0022_documentbundle"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentbundlemembership",
            name="bundle_item_type",
            field=models.CharField(
                blank=True,
                max_length=128,
                verbose_name="bundle item type",
            ),
        ),
    ]
