# Generated by Codex on 2026-05-23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0023_documentbundlemembership_bundle_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentbundle",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=128,
                verbose_name="name",
            ),
        ),
    ]
